apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  aws_access_key_id: QUtJQVpKNjZCVFQzU01GSEU0WEdG
  aws_secret_access_key: YmFuM1RKSTRJVER1Q081a2FXQ1JLZThCZi9xSG5YRHlMdGgyR1dwYQ==
