apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-s3-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-s3-app
  template:
    metadata:
      labels:
        app: flask-s3-app
    spec:
      containers:
      - name: flask-s3-app
        image: flask-s3-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_secret_access_key
        - name: S3_BUCKET
          value: "your-s3-bucket-name"
        - name: AWS_REGION
          value: "ap-southeast-1"

---
apiVersion: v1
kind: Service
metadata:
  name: flask-s3-service
spec:
  selector:
    app: flask-s3-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
